### PR TITLE
Notifications and chained promisses

### PR DESCRIPTION
**Pull request by benel**
Hi @franck-eyraud!

In your PR #63, I've tried to decouple:
- FEATURE #48 (now merged in v3),
- FIX to get notifications on errors (see in this new PR),
- REFACTORING to replace async with chained promisses (see in this new PR).

I may have failed since when I merge the above FIX in current master code (that integrates several new features and fixes), I'm notified that `The operation was aborted`. I'm not sure how to debug this... Any idea?

### CODE REVIEW

**Comment by franck-eyraud** [comment]
> I'm notified that `The operation was aborted`. I'm not sure how to debug this... Any idea?

OK I see. It is indeed difficult because (to me) the error occurs only once in a firefox session. But I could manage to configure the debugger to pause when it happens, and saw that this occurs on a `DOMException` error, which shouldn't be any kind of error that come to the error handler. So it seems (a very first sight) to me a false positive error that could be ignored and do not prevent the extension to work

I committed for now this [patch](https://github.com/Hypertopic/LaSuli/commit/12f193dd8a326abe988d64e1b6d5be573d95d1bf) which at least helps not display this error, and maybe help test if the new features still work correctly. 

Can you confirm that everything seems to work as it should then, or is there still some other issue ?

**Comment by benel** [comment]
> it seems (a very first sight) to me a false positive error that could be ignored and do not prevent the extension to work

OK.

> Can you confirm that everything seems to work as it should then, or is there still some other issue ?

I confirm that your patch makes it work!
I will push your fix (with its patch) and your refactoring. I'm on it.

**Comment by benel** [comment]
> I confirm that your patch makes it work!

Err, in fact I don't have any notification anymore. Only `Error: undefined` in the console for every kind of exceptions...

**Comment by franck-eyraud** [comment]
Arf, right, the test was not correct (precedence in expressions...), sorry didn't have time to fully test yesterday.

[modified patch](https://github.com/franck-eyraud/LaSuli/commit/9594d1427c7c13ce031a11c735b15d9ff353e929)

That said, not sure that this will fully solve the merge, I'm quite puzzle why this DOMException error appears in this Error Handler...

**Comment by benel** [comment]
I didn't notice either.
Thanks.

**Comment by benel** [comment]
Integrated as 03792fd8b168d9e14f4131d557d22b6950c6369b and aacfbdeea2e7bda1f38ed1c37d5575801d214667.

**Pull request closed without merging**
